name: 'Deploy apps'
description: 'Update charts for deploy'
inputs:
  app-name:
    description: 'Application id'
    default: ''
  aws-role:
    description: 'Aws role to apply changes'
    default: ''
  aws-region:
    description: 'Aws region'
    default: 'eu-central-1'
  debug:
    description: 'Debug mode'
    default: false
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    default: ''
  github-token:
    description: 'Github token to pull package to avoid limit rate'
    default: ''
  helm-repo:
    description: 'helm repository'
    default: 'FinalCAD/eks-apps'
  helm-ref:
    descrition: 'Ref to use for pulling helm repo'
    default: 'master'
  registry:
    description: 'Registry name for app'
    default: ''
  sqitch:
    description: 'Only trigger sqitch deploy'
    default: false
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    default: ''
  regions:
    description: 'Regions: eu, ap'
    default: 'eu,ap'
  tag:
    description: 'Tag to deploy'
    default: ''
  override-file:
    description: 'Path relative to project SCM root for override configuration file'
    default: '.finalcad/overrides.yaml'
  additional-override-files:
    description: 'Comma-separated list of additional override files relative to current directory'
    default: ''
  dry-run:
    description: "Don't modify any thing, just print generated files"
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Deprecated version of FinalCAD/AppDeployAction
      shell: bash
      run: |
        echo '::error title=Deprecated version of FinalCAD/AppDeployAction::This version of FinalCAD/AppDeployAction is deprecated use `v3` instead.'
        exit 1
